apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-kube-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-kube-app
  template:
    metadata:
      labels:
        app: my-kube-app
    spec:
      containers:
      - name: my-kube-app
        image: my-kube-app
        imagePullPolicy: Never   # <--- important!
        ports:
        - containerPort: 5000
